version: '3'
services:
  c2:
    container_name: c2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./:/app
    environment:
      - TOKEN=test
      - WORKER_PORT=8000

      