version: '3'
services:
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - TOKEN=test
      - C2_URL=http://181.214.140.244:8888