version: '3'
services:
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      - TOKEN=test
      - C2_URL=http://181.214.140.145:8888
      - WORKER_IP=181.214.140.145